-- begin CARSERVICE_PRODUCT
alter table CARSERVICE_PRODUCT add constraint FK_CARSERVICE_PRODUCT_ON_VENDOR foreign key (VENDOR_ID) references CARSERVICE_VENDOR(ID)^
create unique index IDX_CARSERVICE_PRODUCT_UNIQ_PRODUCT_ID on CARSERVICE_PRODUCT (PRODUCT_ID) ^
create index IDX_CARSERVICE_PRODUCT_ON_VENDOR on CARSERVICE_PRODUCT (VENDOR_ID)^
-- end CARSERVICE_PRODUCT
-- begin CARSERVICE_VENDOR
alter table CARSERVICE_VENDOR add constraint FK_CARSERVICE_VENDOR_ON_USER foreign key (USER) references SEC_USER(ID)^
create unique index IDX_CARSERVICE_VENDOR_UNIQ_VENDOR_NAME on CARSERVICE_VENDOR (VENDOR_NAME) ^
create index IDX_CARSERVICE_VENDOR_ON_USER on CARSERVICE_VENDOR (USER)^
-- end CARSERVICE_VENDOR
-- begin CARSERVICE_SHOP
alter table CARSERVICE_SHOP add constraint FK_CARSERVICE_SHOP_ON_NETWORK foreign key (NETWORK_ID) references CARSERVICE_COMMERCIAL_NETWORK(ID)^
alter table CARSERVICE_SHOP add constraint FK_CARSERVICE_SHOP_ON_PRODUCT foreign key (PRODUCT_ID) references CARSERVICE_PRODUCT(ID)^
create unique index IDX_CARSERVICE_SHOP_UNIQ_NUMBER on CARSERVICE_SHOP (NUMBER) ^
create index IDX_CARSERVICE_SHOP_ON_NETWORK on CARSERVICE_SHOP (NETWORK_ID)^
create index IDX_CARSERVICE_SHOP_ON_PRODUCT on CARSERVICE_SHOP (PRODUCT_ID)^
-- end CARSERVICE_SHOP
-- begin CARSERVICE_COMMERCIAL_NETWORK
create unique index IDX_CARSERVICE_COMMERCIAL_NETWORK_UNIQ_NETWORK_NAME on CARSERVICE_COMMERCIAL_NETWORK (NETWORK_NAME) ^
-- end CARSERVICE_COMMERCIAL_NETWORK
-- begin CARSERVICE_PURCHASE
alter table CARSERVICE_PURCHASE add constraint FK_CARSERVICE_PURCHASE_ON_SHOP foreign key (SHOP_ID) references CARSERVICE_SHOP(ID)^
create index IDX_CARSERVICE_PURCHASE_ON_SHOP on CARSERVICE_PURCHASE (SHOP_ID)^
-- end CARSERVICE_PURCHASE
-- begin CARSERVICE_PRICE_HISTORY
alter table CARSERVICE_PRICE_HISTORY add constraint FK_CARSERVICE_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references CARSERVICE_PRODUCT(ID)^
alter table CARSERVICE_PRICE_HISTORY add constraint FK_CARSERVICE_PRICE_HISTORY_ON_SHOP foreign key (SHOP_ID) references CARSERVICE_SHOP(ID)^
create index IDX_CARSERVICE_PRICE_HISTORY_ON_PRODUCT on CARSERVICE_PRICE_HISTORY (PRODUCT_ID)^
create index IDX_CARSERVICE_PRICE_HISTORY_ON_SHOP on CARSERVICE_PRICE_HISTORY (SHOP_ID)^
-- end CARSERVICE_PRICE_HISTORY
