-- begin CARSERVICE_PRODUCT
alter table CARSERVICE_PRODUCT add constraint FK_CARSERVICE_PRODUCT_ON_VENDOR_NAME foreign key (VENDOR_NAME) references CARSERVICE_VENDOR(ID)^
create index IDX_CARSERVICE_PRODUCT_ON_VENDOR_NAME on CARSERVICE_PRODUCT (VENDOR_NAME)^
-- end CARSERVICE_PRODUCT
-- begin CARSERVICE_VENDOR
alter table CARSERVICE_VENDOR add constraint FK_CARSERVICE_VENDOR_ON_USER foreign key (USER) references SEC_USER(ID)^
create index IDX_CARSERVICE_VENDOR_ON_USER on CARSERVICE_VENDOR (USER)^
-- end CARSERVICE_VENDOR
-- begin CARSERVICE_SHOP
alter table CARSERVICE_SHOP add constraint FK_CARSERVICE_SHOP_ON_NETWORK foreign key (NETWORK_ID) references CARSERVICE_COMMERCIAL_NETWORK(ID)^
create index IDX_CARSERVICE_SHOP_ON_NETWORK on CARSERVICE_SHOP (NETWORK_ID)^
-- end CARSERVICE_SHOP
