alter table CARSERVICE_PRICE_HISTORY add constraint FK_CARSERVICE_PRICE_HISTORY_ON_PRODUCT foreign key (PRODUCT_ID) references CARSERVICE_PRODUCT(ID);
alter table CARSERVICE_PRICE_HISTORY add constraint FK_CARSERVICE_PRICE_HISTORY_ON_SHOP foreign key (SHOP_ID) references CARSERVICE_SHOP(ID);
create index IDX_CARSERVICE_PRICE_HISTORY_ON_PRODUCT on CARSERVICE_PRICE_HISTORY (PRODUCT_ID);
create index IDX_CARSERVICE_PRICE_HISTORY_ON_SHOP on CARSERVICE_PRICE_HISTORY (SHOP_ID);
