alter table CARSERVICE_PRICE_HISTORY alter column SHOP_NAME rename to SHOP_NAME__U35110 ^
alter table CARSERVICE_PRICE_HISTORY drop constraint FK_CARSERVICE_PRICE_HISTORY_ON_SHOP_NAME ;
drop index IDX_CARSERVICE_PRICE_HISTORY_ON_SHOP_NAME ;
alter table CARSERVICE_PRICE_HISTORY add column SHOP_ID varchar(36) ;
