alter table CARSERVICE_PRICE_HISTORY add constraint FK_CARSERVICE_PRICE_HISTORY_ON_SHOP foreign key (SHOP_ID) references CARSERVICE_SHOP(ID);
create index IDX_CARSERVICE_PRICE_HISTORY_ON_SHOP on CARSERVICE_PRICE_HISTORY (SHOP_ID);
