alter table CARSERVICE_PURCHASE add constraint FK_CARSERVICE_PURCHASE_ON_SHOP foreign key (SHOP_ID) references CARSERVICE_SHOP(ID);
create index IDX_CARSERVICE_PURCHASE_ON_SHOP on CARSERVICE_PURCHASE (SHOP_ID);
