alter table CARSERVICE_SHOP add constraint FK_CARSERVICE_SHOP_ON_NETWORK foreign key (NETWORK_ID) references CARSERVICE_COMMERCIAL_NETWORK(ID);
create index IDX_CARSERVICE_SHOP_ON_NETWORK on CARSERVICE_SHOP (NETWORK_ID);
