alter table CARSERVICE_PRODUCT add constraint FK_CARSERVICE_PRODUCT_ON_VENDOR foreign key (VENDOR_ID) references CARSERVICE_VENDOR(ID);
create index IDX_CARSERVICE_PRODUCT_ON_VENDOR on CARSERVICE_PRODUCT (VENDOR_ID);
