alter table CARSERVICE_PRODUCT add constraint FK_CARSERVICE_PRODUCT_ON_VENDOR_NAME foreign key (VENDOR_NAME) references CARSERVICE_VENDOR(ID);
create index IDX_CARSERVICE_PRODUCT_ON_VENDOR_NAME on CARSERVICE_PRODUCT (VENDOR_NAME);
